name = "NormalModes"
uuid = "07f7ac4a-38ba-4abf-9c7e-757259fae6a4"
authors = ["Benoît Richard <benoit.richard@desy.de> and contributors"]
version = "0.1.0"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6"
Chain = "0.5"
Distributions = "0.25 - 0.28"
StatsBase = "0.33"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
